FROM ubuntu:16.04 as theia
RUN apt-get update && apt-get install -y curl wget build-essential git && \
    echo 'export PATH=/opt/conda/bin:$PATH' > /etc/profile.d/conda.sh && \
    wget --quiet https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/anaconda.sh && \
    /bin/bash ~/anaconda.sh -b -p /opt/conda && \
    rm ~/anaconda.sh && \
    apt remove -y python3.5 python2.7 python-minimal && apt autoremove -y && cp /opt/conda/bin/python /usr/bin/python
ENV PATH /opt/conda/bin:$PATH
ENV LD_LIBRARY_PATH /opt/conda/lib:$LD_LIBRARY_PATH
RUN conda install -c conda-forge yarn nodejs=8.10
RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - && \
    echo "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial main" > /etc/apt/sources.list.d/llvm.list && \
    apt-get update && apt-get install -y clang-tools-8 && \
    ln -s /usr/bin/clangd-8 /usr/bin/clangd
RUN pip install \
    python-language-server \
    flake8 \
    autopep8
RUN git clone --depth 1 https://github.com/theia-ide/theia
ADD theia-package.json /theia/package.json 
RUN cd theia && \
    yarn --cache-folder ./ycache && rm -rf ./ycache && \
    yarn theia build && echo "Theia Finished"
